Milestone: Friendship
cyonii/ror-social-scaffold pull request #3
Opened 2021-01-15 16:47 UTC by cyonii

- Modelled friendship concept
- Tested all Models

2021-01-15 23:32 UTC, blackpintz requested changes
# Status: Changes Required 🛑 

## Hello team 👋

**Great job on this milestone 💪. However, there are a few changes needed before the project can be approved.**

### Note: I will use examples to explain.
1). **I have two users, Jen and Mercy. Jen sends Mercy a friend request. Mercy can not be able to accept the request because she only sees the cancel request button.**
2). **Please add a profile page for every user. It should already be there from the forked repo. Ensure that when a user receives a friend request, they can see it on their profile page as well. See [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from pathwright.**
3). **A user should not see another user's posts unless they are confirmed friends. See [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from pathwright.**

4). **I get the error below when I run `rubocop -a`.**
![rubocop](https://user-images.githubusercontent.com/38922385/104786677-a2a36a80-579e-11eb-84a3-8d76f73d442b.png)

5). **Add tests for your views.**

6). **Remove logic in `layouts/application.html.erb` file in views directory.**

7). **Fix the linter errors.**

8). **Check for more in the comments below.**

## Happy coding 🥂.

**PS: You can reach me on slack (Rose Wanjohi).**

2021-01-15 23:32 UTC, blackpintz commented on app/models/comment.rb
> +            length: { maximum: 200, too_long: '200 characters in comment is the maximum allowed.' }
The validation test for this is not complete. You have omitted tests for length. Hint: You can use [shoulda Matchers](http://matchers.shoulda.io/docs/v4.0.1/Shoulda/Matchers/ActiveModel.html) for this.
Make a similar change for `post.rb` and `user.rb` files.

2021-01-15 23:32 UTC, blackpintz commented on app/models/user.rb
> +  end
Add tests for the above methods. If however, you can make them private then you don't have to write tests for them.

2021-01-15 23:32 UTC, blackpintz commented on app/controllers/friendships_controller.rb
> +  end
Remove the commented code.

2021-01-18 15:28 UTC, cyonii commented
About Number 2: Clicking on a user's name will take you to their profile. Kindly let me know if this is not expected case.

2021-01-18 17:39 UTC, mimipeshy commented
### STATUS : APPROVED :partying_face: 

Hey team @cyonii :wave: :wave: , great job on working on all requirements needed. This project is therefore approved. Go ahead and merge :smile: 
All the best in the next milestones!!!

Regards
Peris Ndanu

2021-01-18 18:00 UTC, merged